### ISSUE TITLE
The client cannot be accessed

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-client#1174]
One of the latest updates caused, that the client cannot be shown. The following error appears:
```
spinner.module.ts:8 Uncaught ReferenceError: Cannot access 'OpenSlidesOverlayModule' before initialization
    at Module.OpenSlidesOverlayModule (spinner.module.ts:8:39)
    at Module.65300 (interaction-service.module.ts:6:35)
    at __webpack_require__ (bootstrap:19:1)
    at Module.50114 (home.config.ts:15:3)
    at __webpack_require__ (bootstrap:19:1)
    at Module.50492 (interaction-service.module.ts:6:58)
    at __webpack_require__ (bootstrap:19:1)
    at Module.80518 (meetings.config.ts:15:3)
    at __webpack_require__ (bootstrap:19:1)
    at Module.98603 (index.ts:1:51)
```

**Comment by jsangmeister** [comment]
And here I am trying to find out what I destroyed in my PR...
