### ISSUE TITLE
[RTF] accounts cannot be deleted

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2494]
Accounts cannot be deleted 

**current behaviour:**
if you try to delete an account which is in a meeting it's not deleted and throws an error in the console:

> ERROR Error: Uncaught (in promise): Error: <html>
> <head>
>  <title>Internal Server Error</title>
>   </head>
>   <body>
>     <h1><p>Internal Server Error</p></h1>
>     
>   </body>
> </html>
> 
> Error: <html>
>   <head>
>     <title>Internal Server Error</title>
>   </head>
>   <body>
>     <h1><p>Internal Server Error</p></h1>
>     
>   </body>
> </html>

**wanted behaviour:**
the account(s) should be deletable.

**Comment by jsangmeister** [comment]
That looks like a backend error. Can you provide the exact payload and the logs of the backend and datastore?

**Comment by Elblinator** [comment]
> That looks like a backend error. Can you provide the exact payload and the logs of the backend and datastore?

[{"action":"user.delete","data":[{"id":1061}]}]

and 

POST https://rtf-testintern.staging.openslides.com/system/action/handle_request 500

**Comment by jsangmeister** [comment]
Traceback:
```
INFO:openslides_backend.shared.handlers.base_handler:Performing action user.delete.
[2023-07-06 07:43:51 +0000] [81] [ERROR] Error handling request /system/action/handle_request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 271, in handle
    keepalive = self.handle_request(req, conn)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 323, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/app/openslides_backend/http/application.py", line 103, in __call__
    return self.wsgi_application(environ, start_response)
  File "/app/openslides_backend/http/application.py", line 93, in wsgi_application
    response = self.dispatch_request(request)
  File "/app/openslides_backend/http/application.py", line 44, in dispatch_request
    response_body, access_token = view_instance.dispatch(request)
  File "/app/openslides_backend/http/views/base_view.py", line 117, in dispatch
    return func(request)
  File "/app/openslides_backend/http/views/action_view.py", line 46, in action_route
    response = handle_action_in_worker_thread(
  File "/app/openslides_backend/action/action_worker.py", line 57, in handle_action_in_worker_thread
    raise action_worker_thread.exception
  File "/app/openslides_backend/action/action_worker.py", line 235, in run
    self.response = self.handler.handle_request(
  File "/app/openslides_backend/action/action_handler.py", line 115, in handle_request
    results = self.execute_write_requests(self.parse_actions, payload)
  File "/app/openslides_backend/action/action_handler.py", line 156, in execute_write_requests
    write_requests, data = get_write_requests(*args)
  File "/app/openslides_backend/action/action_handler.py", line 194, in parse_actions
    write_request, results = self.perform_action(
  File "/app/openslides_backend/action/action_handler.py", line 241, in perform_action
    write_request, results = action.perform(
  File "/app/openslides_backend/action/action.py", line 184, in perform
    relation_updates = self.handle_relation_updates(instance)
  File "/app/openslides_backend/action/action.py", line 339, in handle_relation_updates
    relation_updates = self.relation_manager.get_relation_updates(
  File "/app/openslides_backend/action/relations/relation_manager.py", line 71, in get_relation_updates
    self.process_relation_element(fqfield, relations_element, relations)
  File "/app/openslides_backend/action/relations/relation_manager.py", line 128, in process_relation_element
    relation_update_element = self.merge_relation_elements(
  File "/app/openslides_backend/action/relations/relation_manager.py", line 198, in merge_relation_elements
    raise NotImplementedError()
```

**Comment by reiterl** [comment]
Add a test case in the backend to show the error.
https://github.com/OpenSlides/openslides-backend/pull/1839
Yes, it is a backend problem. I don't understand the relation handling at that point, so I don't
try to fix it. @jsangmeister  Please look at this problem.
