### ISSUE TITLE
Fix Settings for Orga-admin

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#2590]
**Description:**
An orga-admin cannot save changes in the orga-settings. If anything (on the orga-level) is changed and the orga-admin tries to save the change, nothing happens.

**Wanted behaviour:**
The orga-admin should be able to save changes in the orga-settings.

**Comment by jsangmeister** [comment]
In dev mode:
```
ERROR TypeError: Cannot read properties of null (reading 'pristine')
    at OrganizationSettingsComponent.onSubmit (organization-settings.component.ts:139:47)
    at OrganizationSettingsComponent_Template_os_head_bar_saveEvent_0_listener (organization-settings.component.html:5:18)
    at executeListenerWithErrorHandling (core.mjs:15679:16)
    at Object.wrapListenerIn_markDirtyAndPreventDefault [as next] (core.mjs:15714:22)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
    at SafeSubscriber.next (Subscriber.js:31:18)
    at Subject.js:34:30
    at errorContext (errorContext.js:19:9)
    at EventEmitter_.next (Subject.js:27:21)
```
Seems to me like it is tried to access a setting which is only intended for superadmins and therefore hidden.
