### ISSUE TITLE
Prevent Error in console in autopilot

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3524]
**Current behaviour:**
If you look at the dev-console and open the autopilot then the following Error is thrown:
```
ERROR Error: Uncaught (in promise): [object Undefined]
at resolvePromise (zone.js:1193:31)
    at zone.js:1100:17
    at zone.js:1116:33
    at Object.close (autoupdate.service.ts:240:21)
    at ModelRequestService.closeSubscription (model-request.service.ts:139:58)
    at ParticipantSearchSelectorComponent.ngOnDestroy (participant-search-selector.component.ts:125:38)
    at executeOnDestroys (core.mjs:7235:32)
    at cleanUpView (core.mjs:7143:9)
    at destroyViewTree (core.mjs:6971:21)
    at destroyLView (core.mjs:7121:9)
```

**Reproduction:
1. open dev-tools > console
2. navigate to autopilot
3. error is thrown

**Wanted behaviour:**
Whatever creates the Error should be prevented

**Comment by reiterl** [comment]
I cannot reproduce this.

**Comment by bastianjoel** [comment]
This should not have any side effects.

**Comment by bastianjoel** [comment]
I updated the reproduction steps. The error is thrown when for example the participant list is not finished loading and the user navigates away from autopilot.
