### ISSUE TITLE
Fix client reaction if action worker is done too quickly

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#3926]
**Describe the bug**
If an action.worker is done too fast then the client throws a snackbar error and Errors in the console: 

Snackbar text:
"An unknown error occurred"

First Error from the console:
```
Unknown error thrown by the http client:  
NullInjectorError: NullInjectorError: No provider for e!
    at io.get (￼chunk-MUFP2MHQ.js:7:1170)
    at Pn.get (￼chunk-MUFP2MHQ.js:7:10756)
    at Pn.get (￼chunk-MUFP2MHQ.js:7:10756)
    at bg (￼chunk-MUFP2MHQ.js:4:2414)
    at R (￼chunk-MUFP2MHQ.js:4:2490)
    at e.ɵfac [as factory] (￼chunk-P5BJY2OF.js:161:77469)
    at Pn.hydrate (￼chunk-MUFP2MHQ.js:7:11550)
    at Pn.get (￼chunk-MUFP2MHQ.js:7:10672)
    at get actionWorkerWatch (￼chunk-P5BJY2OF.js:4:43288)
    at e.<anonymous> (￼chunk-P5BJY2OF.js:4:43842)
```

Second Error thrown in the console:
```
chunk-P5BJY2OF.js:2 Unknown error thrown by the http client:  
TypeError: this.actionWorkerWatch.watch is not a function
    at e.<anonymous> (chunk-P5BJY2OF.js:4:43860)
    at Generator.next (<anonymous>)
    at h (chunk-EPGI56E7.js:1:1793)
    at u.invoke (polyfills-24N7KSB2.js:1:6410)
    at Object.onInvoke (chunk-MUFP2MHQ.js:7:61623)
    at u.invoke (polyfills-24N7KSB2.js:1:6350)
    at _.run (polyfills-24N7KSB2.js:1:1725)
    at polyfills-24N7KSB2.js:2:554
    at u.invokeTask (polyfills-24N7KSB2.js:1:7035)
    at Object.onInvokeTask (chunk-MUFP2MHQ.js:7:61439)
```

backend log with time stamps:
```
backendaction 2024-07-23T15:04:43.377240591+02:00 INFO:openslides_backend.shared.handlers.base_handler:Performing action user.create.
backendaction 2024-07-23T15:04:44.622692282+02:00 INFO:openslides_backend.shared.handlers.base_handler:Request was successful. Send response now.
backendaction 2024-07-23T15:04:44.759295133+02:00 INFO:openslides_backend.action.action_worker:action_worker: Action (user.create) lasts too long. action_worker/1169 written to database. Get the result from database, when the job is done.
backendaction 2024-07-23T15:04:44.760093912+02:00 INFO:openslides_backend.action.action_worker:finish action_worker 'action_worker/1169' (user.create): 1721739885
```

**How to Reproduce:**
The Error so far was only thrown with the new setup
You need a fast setup to get the action worker response "too" fast
1. on orga-level 
2. create a new account
3. error is thrown

**Expected behaviour**
Even if an action worker is done fast, the client should know how to respond

**Comment by bastianjoel** [comment]
Seems like resolving a circular dependency by loading it on demand is not a good idea. 

To fix this instead of directly calling the `ActionWorkerWatchService` from the `HttpService` we could use http interceptors https://angular.dev/guide/http/interceptors

**Comment by bastianjoel** [comment]
This seems to always happen on `202`.
