### ISSUE TITLE
Fix Error in Console

### ISSUE THREAD

**Issue by Elblinator** [OpenSlides/openslides-client#4416]
**Describe the bug**
If the meeting's language is not english and a motion-detail page is reloaded then there is running an Error through the ocnsole

**How to Reproduce**
1. Create a meeting in the language german (or non english language)
2. Navigate into the meeting 
3. Create a motion
4. On the motion-detail page reload the page 
5. Following Error is running through the console 
```
motion-view.component.ts:206 ERROR Error: Parameter "key" is required and cannot be empty
    at _TranslateService.instant (ngx-translate-core.mjs:696:13)
    at _MotionViewComponent.setTitle (base.component.ts:97:49)
    at _MotionViewComponent.onMotionUpdated (motion-view.component.ts:234:15)
```

**Expected behavior**
What ever is causing this Error should be fixed

**Comment by reiterl** [comment]
I cannot reproduce the failure. Tested with German meeting, motion, motion w. amendments.

**Comment by reiterl** [comment]
I cannot reproduce it.
So I looked at the code. I'm not sure why this happen: It seems like the ViewMotion.getTitle() delivers a undefined, null or perhaps empty string. That should not happen, as title is required. Perhaps broken data?

I still needs a way to reproduce this.

**Comment by reiterl** [comment]
Tested some more, if you enter only one space into the title and save it, you get this error.

**Comment by reiterl** [comment]
I have seen the error message few times with empty spaces in motion view, but not every time. So, I am sure why this happens.

**Comment by reiterl** [comment]
This could also be a problem with the "new" translate service.

**Comment by Elblinator** [comment]
The problem is not singularity in the motion-detail and a bit conceptual.

The same problem also occurs in topic-detail, assignment-detail, participant-detail. And there is a very similar problem in the autopilot. 

I'll update the Issue according to the new findings
