### ISSUE TITLE
Spinner runs forever when using a invalid session

### ISSUE THREAD

**Issue by ostcar** [OpenSlides/openslides-client#545]
* Login with a user
* Stop the server and remove all data: `docker container prune` `docker volume prune`
* Restart the server
* Wait until the client is ready
* On the page with the loggedin user, click on some link

There appears a spinner that does not go away.

In the server logs, I see
```
uth_1              | [04.10.2021 -- 05:29:53]: http://localhost:8000: POST -- /system/auth/who-am-i/ 
auth_1              | [04.10.2021 -- 05:29:53]: Expected content-size: 0 
auth_1              | [04.10.2021 -- 05:29:53]: Incoming request with the following headers:
auth_1              |  {
auth_1              |   host: 'localhost:8000',
auth_1              |   'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0',
auth_1              |   'content-length': '0',
auth_1              |   accept: 'application/json, text/plain, */*',
auth_1              |   'accept-encoding': 'gzip, deflate, br',
auth_1              |   'accept-language': 'de-DE,de;q=0.7,en;q=0.3',
auth_1              |   'cache-control': 'no-cache',
auth_1              |   'content-type': 'application/json',
auth_1              |   cookie: 'refreshId=bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI2YzQzZWU5ZjRlMWRkZWE1YzVkNWQ1YzMyOTMzZDEzYyIsInVzZXJJZCI6MSwiaWF0IjoxNjMzMzIzNzE4LCJleHAiOjE2MzM0MTAxMTh9.DkGm-eW9CrkAS2jf7SCtTiV7nto36A4Nh7b_Wx2H3p4',
auth_1              |   dnt: '1',
auth_1              |   origin: 'https://localhost:8000',
auth_1              |   pragma: 'no-cache',
auth_1              |   referer: 'https://localhost:8000/2/motions/5',
auth_1              |   'sec-fetch-dest': 'empty',
auth_1              |   'sec-fetch-mode': 'cors',
auth_1              |   'sec-fetch-site': 'same-origin',
auth_1              |   te: 'trailers',
auth_1              |   'x-forwarded-for': '172.28.0.1',
auth_1              |   'x-forwarded-proto': 'https'
auth_1              | } 
auth_1              | [04.10.2021 -- 05:29:53]: Set CORS-function 
auth_1              | [04.10.2021 -- 05:29:53]: whoAmI -- cookie: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzZXNzaW9uSWQiOiI2YzQzZWU5ZjRlMWRkZWE1YzVkNWQ1YzMyOTMzZDEzYyIsInVzZXJJZCI6MSwiaWF0IjoxNjMzMzIzNzE4LCJleHAiOjE2MzM0MTAxMTh9.DkGm-eW9CrkAS2jf7SCtTiV7nto36A4Nh7b_Wx2H3p4 
auth_1              | [04.10.2021 -- 05:29:53]: Error while who-am-i 
auth_1              | [04.10.2021 -- 05:29:53]: AuthenticationException [Error]: Not signed in
auth_1              |     at new AuthenticationException (/app/src/core/exceptions/authentication-exception.ts:5:9)
auth_1              |     at AuthService.<anonymous> (/app/src/api/services/auth-service.ts:51:19)
auth_1              |     at Generator.next (<anonymous>)
auth_1              |     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
auth_1              |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
auth_1              |   statusCode: 403,
auth_1              |   title: 'Not signed in'
auth_1              | } 
auth_1              | Stacktrace:
auth_1              |  AuthenticationException [Error]: Not signed in
auth_1              |     at new AuthenticationException (/app/src/core/exceptions/authentication-exception.ts:5:9)
auth_1              |     at AuthService.<anonymous> (/app/src/api/services/auth-service.ts:51:19)
auth_1              |     at Generator.next (<anonymous>)
auth_1              |     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
auth_1              |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
auth_1              |   statusCode: 403,
auth_1              |   title: 'Not signed in'
auth_1              | }
```

I would expect to be redirect to the login view or maybe get some sort of error, that my session is invalid.

**Comment by GabrielInTheWorld** [comment]
This relates to #538
